//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tileset_H
#define METASPRITE_tileset_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tileset_TILE_ORIGIN 0
#define tileset_TILE_W 8
#define tileset_TILE_H 8
#define tileset_WIDTH 96
#define tileset_HEIGHT 192
#define tileset_TILE_COUNT 40
#define tileset_PALETTE_COUNT 2
#define tileset_COLORS_PER_PALETTE 4
#define tileset_TOTAL_COLORS 8
#define tileset_MAP_ATTRIBUTES tileset_map_attributes
#define tileset_MAP_ATTRIBUTES_WIDTH 12
#define tileset_MAP_ATTRIBUTES_HEIGHT 24
#define tileset_MAP_ATTRIBUTES_PACKED_WIDTH 12
#define tileset_MAP_ATTRIBUTES_PACKED_HEIGHT 24
extern const unsigned char tileset_map[288];
extern const unsigned char tileset_map_attributes[288];

BANKREF_EXTERN(tileset)

extern const palette_color_t tileset_palettes[8];
extern const uint8_t tileset_tiles[640];

#endif
