//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tileset_H
#define METASPRITE_tileset_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tileset_TILE_ORIGIN 0
#define tileset_TILE_W 8
#define tileset_TILE_H 8
#define tileset_WIDTH 48
#define tileset_HEIGHT 16
#define tileset_TILE_COUNT 4
#define tileset_PALETTE_COUNT 2
#define tileset_COLORS_PER_PALETTE 4
#define tileset_TOTAL_COLORS 8
#define tileset_MAP_ATTRIBUTES tileset_map_attributes
#define tileset_MAP_ATTRIBUTES_WIDTH 6
#define tileset_MAP_ATTRIBUTES_HEIGHT 2
#define tileset_MAP_ATTRIBUTES_PACKED_WIDTH 6
#define tileset_MAP_ATTRIBUTES_PACKED_HEIGHT 2
extern const unsigned char tileset_map[12];
extern const unsigned char tileset_map_attributes[12];

BANKREF_EXTERN(tileset)

extern const palette_color_t tileset_palettes[8];
extern const uint8_t tileset_tiles[64];

#endif
