//AUTOGENERATED FILE FROM png2asset (placeholder: copy of player_idle, rename cat_idle)
#ifndef METASPRITE_CAT_IDLE_H
#define METASPRITE_CAT_IDLE_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define cat_idle_TILE_ORIGIN 0
#define cat_idle_TILE_W 8
#define cat_idle_TILE_H 16
#define cat_idle_WIDTH 16
#define cat_idle_HEIGHT 32
#define cat_idle_TILE_COUNT 20
#define cat_idle_PALETTE_COUNT 1
#define cat_idle_COLORS_PER_PALETTE 4
#define cat_idle_TOTAL_COLORS 4
#define cat_idle_PIVOT_X 8
#define cat_idle_PIVOT_Y 32
#define cat_idle_PIVOT_W 16
#define cat_idle_PIVOT_H 32
extern const metasprite_t* const cat_idle_metasprites[4];

BANKREF_EXTERN(cat_idle)

extern const palette_color_t cat_idle_palettes[4];
extern const uint8_t cat_idle_tiles[320];

#endif
