//AUTOGENERATED FILE FROM png2asset (placeholder: copy of player_idle for cutscene NPC)
#ifndef METASPRITE_CUTSCENE_NPC_H
#define METASPRITE_CUTSCENE_NPC_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define cutscene_npc_TILE_ORIGIN 0
#define cutscene_npc_TILE_W 8
#define cutscene_npc_TILE_H 16
#define cutscene_npc_WIDTH 16
#define cutscene_npc_HEIGHT 32
#define cutscene_npc_TILE_COUNT 20
#define cutscene_npc_PALETTE_COUNT 1
#define cutscene_npc_COLORS_PER_PALETTE 4
#define cutscene_npc_TOTAL_COLORS 4
#define cutscene_npc_PIVOT_X 8
#define cutscene_npc_PIVOT_Y 32
#define cutscene_npc_PIVOT_W 16
#define cutscene_npc_PIVOT_H 32
extern const metasprite_t* const cutscene_npc_metasprites[4];

BANKREF_EXTERN(cutscene_npc)

extern const palette_color_t cutscene_npc_palettes[4];
extern const uint8_t cutscene_npc_tiles[320];

#endif
