//AUTOGENERATED FILE FROM png2asset (placeholder: copy of player_idle for cutscene use)
#ifndef METASPRITE_CUTSCENE_PLAYER_H
#define METASPRITE_CUTSCENE_PLAYER_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define cutscene_player_TILE_ORIGIN 0
#define cutscene_player_TILE_W 8
#define cutscene_player_TILE_H 16
#define cutscene_player_WIDTH 16
#define cutscene_player_HEIGHT 32
#define cutscene_player_TILE_COUNT 20
#define cutscene_player_PALETTE_COUNT 1
#define cutscene_player_COLORS_PER_PALETTE 4
#define cutscene_player_TOTAL_COLORS 4
#define cutscene_player_PIVOT_X 8
#define cutscene_player_PIVOT_Y 32
#define cutscene_player_PIVOT_W 16
#define cutscene_player_PIVOT_H 32
extern const metasprite_t* const cutscene_player_metasprites[4];

BANKREF_EXTERN(cutscene_player)

extern const palette_color_t cutscene_player_palettes[4];
extern const uint8_t cutscene_player_tiles[320];

#endif
