//AUTOGENERATED FILE FROM png2asset (renamed: Alex_idle_16x16 -> player_idle)
#ifndef METASPRITE_PLAYER_IDLE_H
#define METASPRITE_PLAYER_IDLE_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define player_idle_TILE_ORIGIN 0
#define player_idle_TILE_W 8
#define player_idle_TILE_H 16
#define player_idle_WIDTH 16
#define player_idle_HEIGHT 32
#define player_idle_TILE_COUNT 20
#define player_idle_PALETTE_COUNT 1
#define player_idle_COLORS_PER_PALETTE 4
#define player_idle_TOTAL_COLORS 4
#define player_idle_PIVOT_X 8
#define player_idle_PIVOT_Y 32
#define player_idle_PIVOT_W 16
#define player_idle_PIVOT_H 32
extern const metasprite_t* const player_idle_metasprites[4];

BANKREF_EXTERN(player_idle)

extern const palette_color_t player_idle_palettes[4];
extern const uint8_t player_idle_tiles[320];

#endif
