//AUTOGENERATED FILE FROM png2asset (renamed: Alex_run_16x16 -> player_run)
#ifndef METASPRITE_PLAYER_RUN_H
#define METASPRITE_PLAYER_RUN_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define player_run_TILE_ORIGIN 0
#define player_run_TILE_W 8
#define player_run_TILE_H 16
#define player_run_WIDTH 16
#define player_run_HEIGHT 32
#define player_run_TILE_COUNT 80
#define player_run_PALETTE_COUNT 2
#define player_run_COLORS_PER_PALETTE 4
#define player_run_TOTAL_COLORS 8
#define player_run_PIVOT_X 8
#define player_run_PIVOT_Y 32
#define player_run_PIVOT_W 16
#define player_run_PIVOT_H 32
extern const metasprite_t* const player_run_metasprites[24];

BANKREF_EXTERN(player_run)

extern const palette_color_t player_run_palettes[8];
extern const uint8_t player_run_tiles[1280];

#endif
